version: "3.7"

services:
  app:
    container_name: staticapp
    image: staticapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8184:8080"
    volumes:
      - "./:/staticapp"
    working_dir: /staticapp
